export const metadata = {
    title: 'Tega',
    description: 'Generated by Next.js',
    icon: '/favicon.ico',
};

import { ThemeProvider } from '@/providers/theme-provider';
import '../globals.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
