import type { Metadata } from 'next';
import '@/app/globals.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from './components/app-sidebar';
import { Separator } from '@/components/ui/separator';
import {
    Breadcrumb,
    BreadcrumbList,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbSeparator,
    BreadcrumbPage,
} from '@/components/ui/breadcrumb';
import { ProjectProvider } from '@/providers/project-provider';
import { fetchInitialUser } from '@/providers/api/fetch-initial-user';
import { fetchInitialProjects, getActiveProject } from '@/providers/api/fetch-projects';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialUser = await fetchInitialUser();
    const initialProjects = await fetchInitialProjects();
    const initialActiveProject = await getActiveProject(initialProjects || []);

    if (initialUser && initialProjects && initialActiveProject) {
        return (
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <AuthProvider initialUser={initialUser}>
                        <ProjectProvider
                            initialProjects={initialProjects}
                            initialActiveProjects={initialActiveProject}
                        >
                            <ThemeProvider
                                attribute="class"
                                defaultTheme="system"
                                enableSystem
                                disableTransitionOnChange
                            >
                                <SidebarProvider>
                                    <AppSidebar />
                                    <SidebarInset className="bg-sidebar p-2">
                                        <div className="relative flex w-full flex-1 flex-col shadow bg-background rounded-xl">
                                            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                                                <div className="flex items-center gap-2 px-4">
                                                    <SidebarTrigger className="-ml-1" />
                                                    <Separator
                                                        orientation="vertical"
                                                        className="mr-2 h-4"
                                                    />
                                                    <Breadcrumb>
                                                        <BreadcrumbList>
                                                            <BreadcrumbItem className="hidden md:block">
                                                                <BreadcrumbLink href="#">
                                                                    Building Your Application
                                                                </BreadcrumbLink>
                                                            </BreadcrumbItem>
                                                            <BreadcrumbSeparator className="hidden md:block" />
                                                            <BreadcrumbItem>
                                                                <BreadcrumbPage>
                                                                    Data Fetching
                                                                </BreadcrumbPage>
                                                            </BreadcrumbItem>
                                                        </BreadcrumbList>
                                                    </Breadcrumb>
                                                </div>
                                            </header>
                                            <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                                                {children}
                                            </div>
                                        </div>
                                    </SidebarInset>
                                </SidebarProvider>
                            </ThemeProvider>
                        </ProjectProvider>
                    </AuthProvider>
                </body>
            </html>
        );
    }

    redirect('/auth/login');
}
