import '../globals.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { getInitialUser } from '@/hooks/use-initial-user';

export const metadata = {
    title: 'Tega',
    description: 'Generated by Next.js',
    icon: '/favicon.ico',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialUser = await getInitialUser();

    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <AuthProvider initialUser={initialUser}>
                    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
