import type { Metadata } from 'next';
import '../globals.css';
import { ThemeProvider } from '@/providers/teme-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { api } from '@/lib/api';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: 'Tega',
    description: 'Generated by create next app',
};

async function getInitialUser() {
    try {
        const res = await api.auth.user();

        return res.success ? res.data : null;
    } catch (e) {
        console.log(e);
        return null;
    }
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialUser = await getInitialUser();

    if (!initialUser) {
        redirect(`/auth/login`);
    }

    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <AuthProvider initialUser={initialUser}>
                    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
