import type { Metadata } from 'next';
import '../globals.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { api } from '@/lib/api';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from './components/AppSidebar';
import { ThemeTogler } from './components/header/ThemeToggle';
import { redirect } from 'next/navigation';
import { getInitialUser } from '@/hooks/use-initial-user';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialUser = await getInitialUser();

    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <AuthProvider initialUser={initialUser}>
                    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                        <SidebarProvider>
                            <AppSidebar />
                            <SidebarInset className="bg-sidebar p-2">
                                <div className="relative lg:px-6 flex w-full flex-1 flex-col shadow bg-background rounded-xl">
                                    <div className="mt-4">
                                        <ThemeTogler />
                                    </div>
                                    {children}
                                </div>
                            </SidebarInset>
                        </SidebarProvider>
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
