/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    /** Authenticate user */
    post: {
      parameters: {
        body: {
          /** Login credentials */
          request: definitions["req.LoginUserRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["res.SuccessResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["res.ErrorResponse"];
        };
      };
    };
  };
  "/auth/logout": {
    /** Logout user */
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["res.SuccessResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["res.ErrorResponse"];
        };
      };
    };
  };
  "/auth/register": {
    /** Register user */
    post: {
      parameters: {
        body: {
          /** Register credentials */
          request: definitions["req.RegisterUserRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["res.SuccessResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["res.ErrorResponse"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["res.ErrorResponse"];
        };
      };
    };
  };
}

export interface definitions {
  "errs.AppError": {
    code?: string;
    details?: unknown;
    message?: string;
    status?: number;
  };
  "req.LoginUserRequest": {
    email: string;
    password: string;
  };
  "req.RegisterUserRequest": {
    email: string;
    name: string;
    password: string;
  };
  "res.ErrorResponse": {
    error?: definitions["errs.AppError"];
    /** @example false */
    success?: boolean;
  };
  "res.SuccessResponse": {
    /** @example true */
    success?: boolean;
  };
}

export interface operations {}

export interface external {}
