import type { Metadata } from 'next';
import '../globals.css';
import { ThemeProvider } from '@/providers/teme-provider';
import { DashboardHeader } from './components/DashboadHeader';
import { AuthProvider } from '@/providers/auth-context';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <AuthProvider>
                    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                        <DashboardHeader />
                        {children}
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
