import '@/app/globals.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { fetchInitialUser } from '@/providers/api/fetch-initial-user';

export const metadata = {
    title: 'Tega',
    description: 'Generated by Next.js',
    icon: '/favicon.ico',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialUser = await fetchInitialUser();

    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <AuthProvider initialUser={initialUser}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
